name: Publish NuGet package

on:
  push:
    tags:
      - 'v*' # バージョンタグをプッシュしたときに実行

jobs:
  publish:
    permissions:
      contents: read
      id-token: write # OIDCトークン発行のために必要
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    # ビルド & パック 基本
    - name: dotnet pack Base
      run: dotnet pack ./src/MediaFoundation-2010.sln -c Release -o ./bin

    # ビルド & パック 拡張
    - name: dotnet pack Extension
      run: dotnet pack ./src.mfext/MediaFoundation.Extension-2010.sln -c Release -o ./bin

    # NuGet/loginアクションでOIDCトークンを使って短命トークンを取得
    - name: NuGet Login
      uses: NuGet/login@d22cc5f58ff5b88bf9bd452535b4335137e24544 # v1.0.0
      id: login
      with:
        user: CeresSoft # NuGetのユーザー名を指定、Orgアカウントでもユーザー名となる

    # 取得した短命トークンを使ってビルドした複数パッケージを公開
    - name: Push package Base
      run: dotnet nuget push ./bin/*.nupkg --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" --source https://api.nuget.org/v3/index.json
